version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'nestjs_graphql'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'graphql_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
